[tool.poetry]
name = "mbt-python"
version = "0.1.0"
description = "TODO:"
authors = ["Daniel Tisdall <daniel@informal.systems>"]

[tool.poetry.dependencies]
python = "^3.9.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^21.10b0", allow-prereleases = true}
pytest-cov = "^3.0.0"
pre-commit = "^2.15.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
